spring.application.name=Oneshop
# ======================
# DATABASE CONFIG
# ======================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=OneShop;encrypt=false
spring.datasource.username=sa
spring.datasource.password=23110223
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ======================
# THYMELEAF
# ======================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.web.resources.static-locations=classpath:/static/

#spring.thymeleaf.cache=false


# ======================
# EMAIL CONFIG
# ======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyendinhhuylop91@gmail.com
spring.mail.password=glpr orhp fvfa wnfx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ======================
# JWT
# ======================
app.jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
app.jwt.expiration=3600000

# ======================
# SERVER
# ======================
server.port=8080


